//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalProjektWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescriptions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prescriptions()
        {
            this.Visits = new HashSet<Visits>();
        }
    
        public int idPrescr { get; set; }
        public Nullable<int> idHosInf { get; set; }
        public Nullable<int> idDoc { get; set; }
        public Nullable<int> idPrDr { get; set; }
        public Nullable<int> idPat { get; set; }
        public Nullable<System.DateTime> prDate { get; set; }
        public string comment { get; set; }
    
        public virtual Doctors Doctors { get; set; }
        public virtual HospitalInfo HospitalInfo { get; set; }
        public virtual Patients Patients { get; set; }
        public virtual PrescriptionDrugs PrescriptionDrugs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visits> Visits { get; set; }
    }
}
