//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalProjektWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visits
    {
        public int idVis { get; set; }
        public Nullable<int> idDoc { get; set; }
        public Nullable<int> idPat { get; set; }
        public Nullable<System.DateTime> DateOfVisit { get; set; }
        public Nullable<System.TimeSpan> TimeOfVisit { get; set; }
        public string Symptoms { get; set; }
        public string Diagnosis { get; set; }
        public Nullable<int> idDis { get; set; }
        public Nullable<int> idPrescr { get; set; }
        public string sickLeave { get; set; }
        public string recommendations { get; set; }
    
        public virtual Diseases Diseases { get; set; }
        public virtual Doctors Doctors { get; set; }
        public virtual Patients Patients { get; set; }
        public virtual Prescriptions Prescriptions { get; set; }
    }
}
